### ISSUE TITLE
version names

### ISSUE THREAD

**Issue by IzzySoft** [NachiketaVadera/EBookDownloader#1]
I just noticed you always use versionName 1.0 and versionCode 1. Could you please use "real values"? As it currently is, it's hard to (detect an) update: Android will consider all your versions being the same. Thanks!

**Comment by NachiketaVadera** [comment]
Hey. Thanks for the feedback.I'll look into it as soon as I can. You are welcome to send in a PR too. Thank you.

**Comment by IzzySoft** [comment]
@NachiketaVadera I'm not a dev. And changing those values is the task of the "release manager" (you usually adjust them always immediately/shortly before releasing a new version, so that version is reflected). I'd not even know what the next versionName might be :wink:

As a hint: Guessing the next release will be v0.4, and seeing you already have released 3 versions, I'd suggest `versionCode:4` (this is the forth release, you can use this as a counter) and `versionName:0.4` for that.

Additional motivation: I've [added your app to my repo](https://apt.izzysoft.de/fdroid/index/apk/android.nachiketa.ebookdownloader) 10 days ago. So if those who installed it from there (using an F-Droid client) shall see updates, the above is a requirement for that :smile:

**Comment by Poussinou** [comment]
Why don't we try to add this app to the official F-Droid repo?

**Comment by NachiketaVadera** [comment]
@IzzySoft Thank You! Your suggestion and your move to provide with additional motivation have inspired me to do better. I hope the next update you see is what you've wished for.

**Comment by NachiketaVadera** [comment]
@Poussinou I really want to do that but time hasn't allowed me to sit down and go though the process of doing so. Thanks for the suggestion and I promise that I'll try to get the app to F-Droid soon.

**Comment by IzzySoft** [comment]
@NachiketaVadera as you have just explicitly confirmed your willingness to have your app listed in the official repo (thank you for nudging, @Poussinou – I wanted to at least have it ready for that before proposing this step): Shall I trigger the process now (as it usually takes at least a week or more to get started) – or is there something you'd rather wait for? I'd say we're good to go.

**Comment by IzzySoft** [comment]
Ouch, @NachiketaVadera : you forgot to sing v0.4

    ERROR: No signing certificates found in repo/android.nachiketa.ebookdownloader_0.4.apk
    WARNING: Skipping 'android.nachiketa.ebookdownloader_0.4.apk' with invalid signature!

Can you please fix that?

**Comment by IzzySoft** [comment]
> I updated the release with a signed version of the apk.

Sorry to disappoint you, but:

    $ apksigner verify eBooks_v0.4_signed.apk
    DOES NOT VERIFY
    ERROR: No JAR signatures

As this problem didn't exist with the previous version, you must have changed something in your process…

> Yes, I would really appreciate if you could initiate the process.

[here](https://gitlab.com/fdroid/rfp/issues/866) you go :wink:

**Comment by NachiketaVadera** [comment]
> > I updated the release with a signed version of the apk.
> 
> Sorry to disappoint you, but:
> 
> ```
> $ apksigner verify eBooks_v0.4_signed.apk
> DOES NOT VERIFY
> ERROR: No JAR signatures
> ```
> As this problem didn't exist with the previous version, you must have changed something in your process…
> 
> > Yes, I would really appreciate if you could initiate the process.
> 
> [here](https://gitlab.com/fdroid/rfp/issues/866) you go

@IzzySoft Hey! I made a silly mistake while generating the apk. I've solved it and it should be ready to go. For sure this time.

**Comment by IzzySoft** [comment]
> I made a silly mistake while generating the apk.

Happens :rofl: 

> I've solved it and it should be ready to go. For sure this time.

Confirmed, thanks! :+1: To get rid of the remaining warnings (not crucial, just "nice-to-have"), in your build process remove the `META-INF/*.version` files, and move the others to a different place (or remove them as well). Examples (run `apksigner verify eBooks_v0.4_app-release.apk` for the full list):

    WARNING: META-INF/CHANGES not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
    WARNING: META-INF/README.md not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
    WARNING: META-INF/android.arch.core_runtime.version not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
    WARNING: META-INF/android.arch.lifecycle_livedata-core.version not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.

As said, this isn't crucial (I see this with many apps) and doesn't really hurt the user, so take your time with this (or ignore it, as you wish).

Thanks again! App should then show up with the next sync. Please ping me when you released the next version, so I can check whether I can enable auto-update on my end.

**Comment by NachiketaVadera** [comment]
@IzzySoft Yeah, I'll remove these warnings as soon as I can. Nice things are good to have.

**Comment by IzzySoft** [comment]
AFAIR there's also a way to tell gradle to simply ignore them. I'm not a dev, so I don't remember the details (maybe [like this](https://discuss.gradle.org/t/how-can-i-exclude-certain-java-files-from-being-compiled/5287) – e.g. `exclude 'META-INF/*.version`? Though I don't know where that should go then).

Besides: I've enabled auto-update. Please ping me nevertheless so I can check if it worked 😉

**Comment by IzzySoft** [comment]
After our "sleeping beauty" got kissed by me (our bot was on strike since the start of this year), your repo got scanned. Looks good so far, and I hope one of our integrators picks up your app soon to get it build and listed in the official repo.

One minor thing though: [the report](https://gitlab.com/fdroid/rfp/issues/866#note_132732578) included a "scanner-warning" for your gradlew which you might wish to fix (not important for the F-Droid build, but for yours).

**Comment by IzzySoft** [comment]
Another "sleeping beauty"? :rofl: No worries, just fix it before your own next build. Your app's RFP is progressing nicely – looks like your app will be listed soon.

**Comment by NachiketaVadera** [comment]
At this rate, I should change my handle to Aurora 🤣. Yeah, I'll fix it in the next built. Thanks for keeping me on my toes 😁.

**Comment by IzzySoft** [comment]
Metadata were just merged. That usually means the app should show up in less than 2 weeks (unless the build-server has a hickup or the signer is on vacation, or both :scream:)
