### ISSUE TITLE
[Feature Request] Ability to remove or disable history 

### ISSUE THREAD

**Issue by esmoak** [NachiketaVadera/EBookDownloader#3]
It seems that history is retained with no option to disable. It would be nice to have a delete or disable option. 

Thank you. 

edit: I am aware there is a text file I can edit in the file system, but an option to disable would still be nice.

**Comment by ildar** [comment]
It's possible to simply deny Storage permission and you get what you want

**Comment by NachiketaVadera** [comment]
This issue has now been solved.
