### ISSUE TITLE
White text on light background is hard to read

### ISSUE THREAD

**Issue by denilsonsa** [NachiketaVadera/EBookDownloader#4]
The first time I used the app (installed from f-droid), the text was fine and readable. The second time I opened it, this happened:

![screenshot_20190129-080103__01](https://user-images.githubusercontent.com/121676/51890336-1bd00a00-239c-11e9-8998-7ba82bd123da.jpg)

The search results are shown as white text on dark background (following my phone's dark mode theme). This is good.

The history screen, however, doesn't follow my phone's theme and is black text on white background.

Ideally, it would be great if the app used the same colors as the rest of my phone; but I'd also settle for enough contrast with whatever colors you choose.

**Comment by NachiketaVadera** [comment]
@denilsonsa Hello. 

> The history screen, however, doesn't follow my phone's theme and is black text on white background.

The history module has not been completely implemented yet. It was out there to see how the users respond to the possibility of the said feature. The next update should solve this bug.

> Ideally, it would be great if the app used the same colors as the rest of my phone; but I'd also settle for enough contrast with whatever colors you choose.

The app will have a full UI overhaul as soon as I have enough time to make a proper design and start implementing it. The new UI should follow all the standard rules.

Thank you for taking up interest in the app's improvement. 

PS -: If you want an immediate fix or just want to help out even more that what you've done, feel free to send a pull request.

**Comment by NachiketaVadera** [comment]
Hey! The issue has been resolved with the latest commit. Sorry for the delay and thanks for taking up interest.
