### ISSUE TITLE
Translation pt-br

### ISSUE THREAD

**Issue by hanelore** [NachiketaVadera/EBookDownloader#5]
Hi.

What would be the best way to start the translation?

Thanks.

**Comment by NachiketaVadera** [comment]
@hanelore Hey. Thanks for taking up interest for contributing in the app. Honestly, I'm quite new so I don't understand what you mean by translation. Could you provide with some details? 
Thank you.

**Comment by hanelore** [comment]
You are welcome. So, translations of app I have used the native structure (/app/src/main/res/values/pt-br) and change strings.xml file.

Or in some situations, projects use https://crowdin.com/

My question is about your structure. Thanks again.
